import Head from 'next/head'
import { GetServerSideProps } from 'next/types'
import PostService, { IPost } from 'src/service/PostService'

interface PostDetailProps {
    post: IPost
}
const PostDetail = (props: PostDetailProps) => {
    const { post } = props
    return (
        <div>
            <Head>
                <title>{post.title} | Jim Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mx-auto max-w-5xl">
                <h1 className="text-center py-10 text-5xl font-bold">Sturdy Octo Blog</h1>

                <h4 className="text-center font-bold text-2xl mb-6">{post.title}</h4>
                <p>{post.description}</p>
                <div dangerouslySetInnerHTML={{ __html: post.content }}></div>
            </main>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps = async context => {
    const id = context.params?.id as string
    const { data } = await PostService.getDetail(id)
    return { props: { post: data } }
}

export default PostDetail
