import Head from 'next/head'
import { GetServerSideProps } from 'next/types'
import MainLayout from 'src/components/MainLayout'
import PostService, { IPost } from 'src/service/PostService'

interface PostDetailProps {
    post: IPost
}
const PostDetail = (props: PostDetailProps) => {
    const { post } = props
    return (
        <>
            <Head>
                <title>{post.title} | Jim Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainLayout>
                <h4 className="text-center font-bold text-2xl text-slate-900 dark:text-gray-200">
                    {post.title}
                </h4>
                <p className="text-center source mb-8 text-slate-700  underline decoration-sky-500 dark:text-slate-200">
                    By {post.source}
                </p>
                <p className="description  text-slate-700  dark:text-slate-300 xl:text-lg mb-4">
                    {post.description}
                </p>
                <div
                    className="post-content-wrapper  text-slate-700  dark:text-slate-300 xl:text-lg"
                    dangerouslySetInnerHTML={{ __html: post.content }}
                ></div>
            </MainLayout>
        </>
    )
}

export const getServerSideProps: GetServerSideProps = async context => {
    const id = context.params?.id as string
    const { data } = await PostService.getDetail(id)
    return { props: { post: data } }
}

export default PostDetail
