import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import PostList from 'src/components/PostList'
import { ResponseData } from 'src/constants'
import PostService, { IPost } from 'src/service/PostService'
import { getWithPath } from 'src/utils/http'

interface HomeProps {
    posts: ResponseData<IPost[]>
}

const Home = (props: HomeProps) => {
    const { posts } = props
    return (
        <div>
            <Head>
                <title>Jim Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mx-auto max-w-5xl">
                <h1 className="text-center py-10 text-5xl font-bold">Sturdy Octo Blog</h1>

                <PostList posts={posts.data} />
            </main>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps = async context => {
    const data = await PostService.getList()
    return { props: { posts: data } }
}

export default Home
