import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import MainLayout from 'src/components/MainLayout'
import PostList from 'src/components/PostList'
import { ResponseData } from 'src/constants'
import PostService, { IPost } from 'src/service/PostService'
import { getWithPath } from 'src/utils/http'

interface HomeProps {
    posts: ResponseData<IPost[]>
}

const Home = (props: HomeProps) => {
    const { posts } = props
    return (
        <>
            <MainLayout>
                <Head>
                    <title>Jim Blog</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <PostList posts={posts.data} />
            </MainLayout>
        </>
    )
}

export const getServerSideProps: GetServerSideProps = async context => {
    const data = await PostService.getList()
    return { props: { posts: data } }
}

export default Home
